-- Update Target Type Taxonomy

-- Level 1
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Urban and Built-up Area', '');
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Agricultural Land', '');
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Vegetated Land', 'Naturally vegetated land');
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Hydrosphere', '');
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Barren Land', '');
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Reference Material', '');

CREATE TEMPORARY TABLE IF NOT EXISTS `specchio_temp`.`temp_tax_table` AS (SELECT * FROM `specchio`.`taxonomy`);

-- Level 2

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Building', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Urban and Built-up Area'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Lawn', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Urban and Built-up Area'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Swimming Pool', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Urban and Built-up Area'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sport Field', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Urban and Built-up Area'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sealed Surface', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Urban and Built-up Area'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Litter', 'Any form of antrophogene rubbish', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Urban and Built-up Area'));


INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Pastoral Land', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Agricultural Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Crop', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Agricultural Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Ploughed Field', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Agricultural Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Fruit Plantation', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Agricultural Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Vineyard', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Agricultural Land'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Forest', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Vegetated Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Shrub', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Vegetated Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Grassland', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Vegetated Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Moor', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Vegetated Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Burnt Area', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Vegetated Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Deadwood', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Vegetated Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Fern', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Vegetated Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Reed', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Vegetated Land'));


INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Water', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Hydrosphere'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Snow', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Hydrosphere'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Ice', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Hydrosphere'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Bare Soil', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Barren Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sand', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Barren Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Gravel', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Barren Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Scree', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Barren Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Rock', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Barren Land'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Spectralon (White reference)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Reference Material'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Spectralon (Dark reference)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Reference Material'));


delete from `specchio_temp`.`temp_tax_table`;
insert into `specchio_temp`.`temp_tax_table`  (SELECT * FROM `specchio`.`taxonomy`);

-- Level 3

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Roof', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Building'));


INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tartan', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sport Field'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tennis Court', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sport Field'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Soccer Field', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sport Field'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Asphalt', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sealed Surface'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Concrete', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sealed Surface'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Brick', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sealed Surface'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Pavement', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sealed Surface'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Pasture', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Pastoral Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Alpine Pasture', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Pastoral Land'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Hay', 'Cut and dried grass', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Pastoral Land'));


INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Barley', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Crop'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Wheat', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Crop'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Pea', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Crop'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Rye', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Crop'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sugar Beet', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Crop'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Corn', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Crop'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Carrot', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Crop'));





INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Broad-leaved Forest', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Forest'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Coniferous Forest', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Forest'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Mixed Forest', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Forest'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Lake', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Water' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'River', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Water' and parent_id is not null));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Snow (White)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Snow' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Snow (Dirty)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Snow' and parent_id is not null));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Ice (Blue)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Ice' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Ice (Grey)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Ice' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Ice (Bright)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Ice' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Ice (Dark)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Ice' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Ice (Dirty)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Ice' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Ice (With water film)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Ice' and parent_id is not null));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sand (Bright)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sand' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sand (Dark)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sand' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sand (Grey)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sand' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sand (Fine)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sand' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Sand (Coarse)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Sand' and parent_id is not null));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Gravel (Bright)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Gravel' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Gravel (Dark)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Gravel' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Gravel (Fine)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Gravel' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Gravel (Coarse)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Gravel' and parent_id is not null));

-- Level 4

delete from `specchio_temp`.`temp_tax_table`;
insert into `specchio_temp`.`temp_tax_table`  (SELECT * FROM `specchio`.`taxonomy`);

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Roof (Black rubber)', 'Solar water heater mattresses', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Roof' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Roof (Vegetated)', 'Green roof', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Roof' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Roof (Gravel)', 'Gravel covered roof', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Roof' and parent_id is not null));


INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tartan (Blue)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Tartan' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tartan (Red)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Tartan' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tartan (Orange)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Tartan' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tartan (Yellow)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Tartan' and parent_id is not null));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tennis Court (Sand)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Tennis Court' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tennis Court (Grass)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Tennis Court' and parent_id is not null));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Tennis Court (Hardcourt)', 'A hardcourt is a surface or floor on which a sport is played, most usually in reference to tennis courts. They are typically made of rigid materials such as asphalt or concrete, and covered with acrylic material to seal the surface and mark the playing lines, while providing some cushioning.', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Tennis Court' and parent_id is not null));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Soccer Field (Grass)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Soccer Field'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Soccer Field (Artificial)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Soccer Field'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Pavement (Grey)', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Pavement'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Clover', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Pasture'));

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Summer Wheat', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Wheat'));
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `description`, `parent_id`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type'), 'Winter Wheat', '', (select taxonomy_id from `specchio_temp`.`temp_tax_table` where attribute_id = (select `attribute_id` from `specchio`.`attribute` where name = 'Basic Target Type') and name like 'Wheat'));



-- boolean upgrade
INSERT INTO `specchio`.`unit`(`name`, `description`, `short_name`) values('Boolean', 'Boolean value (0 or 1)', 'Boolean');


-- instrumentation upgrade
INSERT INTO `specchio`.`attribute`(`name`, `category_id`, `default_storage_field`, `default_unit_id`, `description`) VALUES ('Reference Panel Levelled', (select category_id from `specchio`.category where name = 'Instrumentation'), 'int_val', (select unit_id from `specchio`.unit where name = 'Boolean'),'Indicates if the reference panel was mounted on a stable support and carefully levelled');


-- Time approximating flags
INSERT INTO `specchio`.`attribute`(`name`, `category_id`, `default_storage_field`, `default_unit_id`, `description`) VALUES ('Acquisition Time Approximated', (select category_id from `specchio`.category where name = 'General'), 'int_val', (select unit_id from `specchio`.unit where name = 'Boolean'),'Indicates if the acquisition time was not properly recorded and had to be approximated by other means');
INSERT INTO `specchio`.`attribute`(`name`, `category_id`, `default_storage_field`, `default_unit_id`, `description`) VALUES ('Acquisition Time (UTC) Approximated', (select category_id from `specchio`.category where name = 'General'), 'int_val', (select unit_id from `specchio`.unit where name = 'Boolean'),'Indicates if the acquisition time (UTC) was not properly recorded and had to be approximated by other means');



-- default unit upgrade
update attribute set default_unit_id = (select unit_id from `specchio`.`unit` where short_name = 'm') where name = 'Height';
update attribute set default_unit_id = (select unit_id from `specchio`.`unit` where name = 'Percent') where name = 'Cloud Cover';
update attribute set default_unit_id = (select unit_id from `specchio`.`unit` where short_name = 'm') where name = 'Sensor Distance';

-- spatial sampling scheme
INSERT INTO `specchio`.`category` (`name`, `string_val`) VALUES ('Sampling Scheme', '');
INSERT INTO `specchio`.`attribute`(`name`, `description`, `category_id`, `default_storage_field`) VALUES ('Spatial Sampling Scheme', '', (select category_id from `specchio`.`category` where name = 'Sampling Scheme'), 'taxonomy_id');

INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `code`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Spatial Sampling Scheme'), 'Cross', '', 'See: VALERI : a network of sites and methodology for the validation of medium spatial resolution land products');
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `code`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Spatial Sampling Scheme'), 'Square (VALERI Scheme)', '', 'See: VALERI : a network of sites and methodology for the validation of medium spatial resolution land products');
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `code`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Spatial Sampling Scheme'), 'Transect', '', 'See: VALERI : a network of sites and methodology for the validation of medium spatial resolution land products');
INSERT INTO `specchio`.`taxonomy` (`attribute_id`, `name`, `code`, `description`) VALUES ((select `attribute_id` from `specchio`.`attribute` where name = 'Spatial Sampling Scheme'), 'Sweep', '', 'Sweep of the target with continous data acquisition');


-- calibration upgrade to store ASD relevant data
ALTER TABLE `specchio`.`calibration` ADD COLUMN `fov` INTEGER NULL DEFAULT NULL;
ALTER TABLE `specchio`.`calibration` ADD COLUMN `name` VARCHAR(100) NULL DEFAULT NULL;

-- Measurement Support Upgrade

INSERT INTO `specchio`.`unit` (`name`, `short_name`) VALUES ('Square Metres', 'm2');

INSERT INTO `specchio`.`attribute`(`name`, `category_id`, `default_storage_field`, `default_unit_id`, `description`) VALUES ('Measurement Support Radius', (select category_id from `specchio`.category where name = 'Sampling Geometry'), 'double_val', (select unit_id from `specchio`.unit where short_name = 'm'),'Radius of the measurement support, i.e. the radius of the projected field of view');
INSERT INTO `specchio`.`attribute`(`name`, `category_id`, `default_storage_field`, `default_unit_id`, `description`) VALUES ('Measurement Support Major Axis', (select category_id from `specchio`.category where name = 'Sampling Geometry'), 'double_val', (select unit_id from `specchio`.unit where short_name = 'm'),'Major axis of the measurement support, i.e. the major axis of the elliptical projected field of view');
INSERT INTO `specchio`.`attribute`(`name`, `category_id`, `default_storage_field`, `default_unit_id`, `description`) VALUES ('Measurement Support Minor Axis', (select category_id from `specchio`.category where name = 'Sampling Geometry'), 'double_val', (select unit_id from `specchio`.unit where short_name = 'm'),'Minor axis of the measurement support, i.e. the minor axis of the elliptical projected field of view');
INSERT INTO `specchio`.`attribute`(`name`, `category_id`, `default_storage_field`, `default_unit_id`, `description`) VALUES ('Measurement Support Area', (select category_id from `specchio`.category where name = 'Sampling Geometry'), 'double_val', (select unit_id from `specchio`.unit where short_name = 'm2'),'Area of the measurement support, i.e. the areas of the projected field of view');







-- db version
INSERT INTO `specchio`.`schema_info` (`version`, `date`) VALUES ('3.22', CURDATE());

